Repository cloudforet-io/api, pull requests merged in 2024-05, with the labels that each got.

#326 Modify response at cost_analysis.DataSourceAccount reset api to empty
  proto/spaceone/api/cost_analysis/v1/data_source_account.proto
Labels: enhancement

#327 Add all_workspaces field at DataSourceRule Actions
  proto/spaceone/api/cost_analysis/v1/data_source_rule.proto
Labels: enhancement

#328 Add analyze api for DataSourceAccount
  proto/spaceone/api/cost_analysis/v1/data_source_account.proto
Labels: enhancement, pass/signedoff

#331 Add WorkspaceConfig at Config service
  proto/spaceone/api/config/v1/workspace_config.proto
Labels: enhancement

#334 Add `is_linked` field at DataSourceAccountInfo
  proto/spaceone/api/cost_analysis/v1/data_source_account.proto
Labels: enhancement

#337 feat: change namespace and metric fields
  proto/spaceone/api/inventory/v1/metric.proto
  proto/spaceone/api/inventory/v1/namespace.proto
Labels: pass/signedoff
