Repository cloudforet-io/api, pull requests merged in 2024-08, with the labels that each got.

#385 Add workspace group template APIs
  proto/spaceone/api/identity/v2/workspace.proto
  proto/spaceone/api/identity/v2/workspace_group.proto
  proto/spaceone/api/identity/v2/workspace_user.proto
Labels: enhancement, pass/signedoff

#386 Update users from list of string to list of dictionary
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#387 Update user info
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#388 Update user group request
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#389 Add workspace_group find API
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#390 Modify Typo
  proto/spaceone/api/identity/v2/workspace_user.proto
Labels: enhancement, fail/signedoff

#393 Add workspace_group_id to the role binding
  proto/spaceone/api/identity/v2/role_binding.proto
Labels: enhancement, pass/signedoff

#395 Add workspace group details API
  proto/spaceone/api/identity/v2/workspace_group_details.proto
Labels: enhancement, pass/signedoff

#396 Modify get_workspace_groups endpoint
  proto/spaceone/api/identity/v2/workspace_group_details.proto
Labels: enhancement, pass/signedoff

#397 Add role_binding_info to WorkspaceGroupInfo
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#398 Modify RoleBindingInfo in workspace group
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#399 Update role_binding_info to workspace group user
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#400 Add WorkspaceGroupUser API and modify WorkspaceGroup API
  proto/spaceone/api/identity/v2/role.proto
  proto/spaceone/api/identity/v2/user_profile.proto
  proto/spaceone/api/identity/v2/workspace_group.proto
  proto/spaceone/api/identity/v2/workspace_group_details.proto
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: enhancement, pass/signedoff

#401 Solve conflict issue between workspace_group and workspace_group
  proto/spaceone/api/identity/v2/workspace_group.proto
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: bug, fail/signedoff

#402 Add workspace_group_id for stat api
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: enhancement, pass/signedoff

#403 Add my workspace group info API
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement, pass/signedoff

#404 Update import path
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: bug, pass/signedoff

#405 Add params_user_id because of injected params
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: enhancement, pass/signedoff

#406 Modify variable name
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: enhancement, pass/signedoff

#407 Add State
  proto/spaceone/api/identity/v2/role.proto
Labels: enhancement, pass/signedoff

#408 Add domain_id, created_at, updated_at to BasicRoleInfo
  proto/spaceone/api/identity/v2/role.proto
Labels: enhancement, pass/signedoff

#410 Add page access field at identity.GrantTokenInfo
  proto/spaceone/api/identity/v2/token.proto
Labels: pass/signedoff

#411 Add `name` field at cost-analysis plugin at SyncedAccountInfo
  proto/spaceone/api/cost_analysis/plugin/job.proto
Labels: enhancement

#409 Remove basic role info
  proto/spaceone/api/identity/v2/role.proto
  proto/spaceone/api/identity/v2/workspace.proto
Labels: enhancement, fail/signedoff, pass/signedoff
