Repository cloudforet-io/api, pull requests merged in 2024-11, with the labels that each got.

#442 Add examples for identity
  proto/spaceone/api/identity/v2/external_auth.proto
  proto/spaceone/api/identity/v2/job.proto
  proto/spaceone/api/identity/v2/project_group.proto
  proto/spaceone/api/identity/v2/token.proto
  proto/spaceone/api/identity/v2/workspace_user.proto
Labels: documentation

#444 docs: Add examples for domain, project, role, user, workspace
  proto/spaceone/api/identity/v2/domain.proto
  proto/spaceone/api/identity/v2/project.proto
  proto/spaceone/api/identity/v2/role.proto
  proto/spaceone/api/identity/v2/user.proto
  proto/spaceone/api/identity/v2/workspace.proto
Labels: documentation, fail/signedoff, pass/signedoff

#445 Add examples for project, provider, schema
  proto/spaceone/api/identity/v2/project.proto
  proto/spaceone/api/identity/v2/provider.proto
  proto/spaceone/api/identity/v2/schema.proto
Labels: documentation, fail/signedoff, pass/signedoff

#446 Initial commit for OpsFlow service
  proto/spaceone/api/opsflow/comment.proto
  proto/spaceone/api/opsflow/event.proto
  proto/spaceone/api/opsflow/task.proto
  proto/spaceone/api/opsflow/task_category.proto
  proto/spaceone/api/opsflow/task_type.proto
Labels: fail/signedoff

#448 fix: typo in task.proto
  proto/spaceone/api/opsflow/comment.proto
  proto/spaceone/api/opsflow/event.proto
  proto/spaceone/api/opsflow/task.proto
  proto/spaceone/api/opsflow/task_category.proto
  proto/spaceone/api/opsflow/task_type.proto
Labels: pass/signedoff

#449 refactor: change opsflow directory
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/event.proto
  proto/spaceone/api/opsflow/v1/task.proto
  proto/spaceone/api/opsflow/v1/task_category.proto
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#451 feat: add assignee_pool field to task_type
  proto/spaceone/api/opsflow/v1/task.proto
  proto/spaceone/api/opsflow/v1/task_category.proto
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#453 fix: add force field to TaskCategoryUpdateRequest message
  proto/spaceone/api/opsflow/v1/task_category.proto
Labels: pass/signedoff

#454 Add Region api to Identity-v2
  proto/spaceone/api/inventory/v2/region.proto
Labels: enhancement, pass/signedoff

#457 Add release workflow
  .github/workflows/dispatch_release.yaml
Labels: enhancement

#458 fix: add update_fields RPC to TaskType, TaskCategory service
  proto/spaceone/api/opsflow/v1/task_category.proto
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#459 Add collector service at inventory-v2
  proto/spaceone/api/identity/v2/agent.proto
  proto/spaceone/api/identity/v2/endpoint.proto
  proto/spaceone/api/inventory_v2/v1/collector.proto
  proto/spaceone/api/inventory_v2/v1/job.proto
  proto/spaceone/api/inventory_v2/v1/job_task.proto
Labels: enhancement

#460 Fix type and remove 'capability' field at collector response
  proto/spaceone/api/inventory_v2/v1/collector.proto
Labels: bug, enhancement

#462 Add metric, metric_data, metric_example
  proto/spaceone/api/inventory_v2/v1/metric.proto
  proto/spaceone/api/inventory_v2/v1/metric_data.proto
  proto/spaceone/api/inventory_v2/v1/metric_example.proto
Labels: enhancement, pass/signedoff

#463 Modify duplicated http api for change-member
  proto/spaceone/api/alert_manager/v1/notification_protocol.proto
Labels: bug

#464 Remove all duplicate http api at alert manager
  proto/spaceone/api/alert_manager/v1/alert.proto
  proto/spaceone/api/alert_manager/v1/event.proto
  proto/spaceone/api/alert_manager/v1/event_rule.proto
  proto/spaceone/api/alert_manager/v1/note.proto
  proto/spaceone/api/alert_manager/v1/plugin/event.proto
  proto/spaceone/api/alert_manager/v1/plugin/webhook.proto
  proto/spaceone/api/alert_manager/v1/service_channel.proto
  proto/spaceone/api/alert_manager/v1/user_channel.proto
  proto/spaceone/api/alert_manager/v1/user_group_channel.proto
Labels: bug
