Repository cloudforet-io/api, pull requests merged in 2024-04, with the labels that each got.

#290 Add MyWorkspaceInfo at UserProfile
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement

#291 Add plugin_options for trusted service account
  proto/spaceone/api/identity/v2/job.proto
  proto/spaceone/api/identity/v2/provider.proto
  proto/spaceone/api/identity/v2/trusted_account.proto
Labels: enhancement

#292 Temporary changed field order
  proto/spaceone/api/identity/v2/service_account.proto
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement

#293 Temporary changed field order at AppInfo
  proto/spaceone/api/identity/v2/app.proto
Labels: enhancement

#294 Recover proto field order for user_profile, service_account, app
  proto/spaceone/api/identity/v2/app.proto
  proto/spaceone/api/identity/v2/service_account.proto
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement, pass/signedoff

#295 Add role_name field at MyWorkspaceInfo
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement

#296 Add trusted_account_id field at project, project_group, workspace info
  proto/spaceone/api/identity/v2/project.proto
  proto/spaceone/api/identity/v2/project_group.proto
  proto/spaceone/api/identity/v2/workspace.proto
Labels: enhancement

#301 Add Agent resource and modify Service Account resource
  proto/spaceone/api/identity/v2/agent.proto
  proto/spaceone/api/identity/v2/service_account.proto
Labels: enhancement, pass/signedoff

#302 Modify cost field type 'float' -> 'double' for cost plugin
  proto/spaceone/api/cost_analysis/plugin/cost.proto
Labels: enhancement, pass/signedoff

#303 Reorder protobuf
  proto/spaceone/api/identity/v2/agent.proto
Labels: enhancement

#304 Add agent_id protobuf
  proto/spaceone/api/identity/v2/agent.proto
Labels: enhancement, pass/signedoff

#306 Remove service_account_id filed at AppInfo
  proto/spaceone/api/identity/v2/app.proto
  proto/spaceone/api/identity/v2/service_account.proto
Labels: enhancement, fail/signedoff

#307 Remove tags field
  proto/spaceone/api/identity/v2/agent.proto
Labels: enhancement, pass/signedoff

#308 Add project_id field
  Makefile
  proto/spaceone/api/identity/v2/agent.proto
Labels: enhancement, fail/signedoff

#309 Delete name field in agent
  proto/spaceone/api/identity/v2/agent.proto
Labels: enhancement, pass/signedoff

#311 Add delete workspace force option
  proto/spaceone/api/identity/v2/workspace.proto
Labels: enhancement

#313 Add update secret data api for DataSource
  proto/spaceone/api/cost_analysis/v1/data_source.proto
Labels: enhancement, pass/signedoff

#314 Add cost-analysis Cost pluin `get_linked_accounts` api
  proto/spaceone/api/cost_analysis/plugin/cost.proto
Labels: enhancement, pass/signedoff

#315 Add DataSourceAccount service
  proto/spaceone/api/cost_analysis/plugin/cost.proto
  proto/spaceone/api/cost_analysis/plugin/job.proto
  proto/spaceone/api/cost_analysis/v1/data_source_account.proto
Labels: enhancement

#316 Add virtual id field at DataSourceAccount
  proto/spaceone/api/cost_analysis/plugin/job.proto
  proto/spaceone/api/cost_analysis/v1/cost.proto
  proto/spaceone/api/cost_analysis/v1/data_source_account.proto
Labels: enhancement

#317 Modify reference_id field type at WorkspaceInfo 'string' -> 'list'
  proto/spaceone/api/identity/v2/workspace.proto
Labels: enhancement

#319 Add MetricExample APIs
  proto/spaceone/api/inventory/v1/metric_example.proto
  proto/spaceone/api/inventory/v1/namespace.proto
Labels: pass/signedoff

#322 Remove unused field at data_source_account.proto
  proto/spaceone/api/cost_analysis/v1/data_source_account.proto
Labels: enhancement

#323 Add connected_workspace_id at DataSourceQuery message
  proto/spaceone/api/cost_analysis/v1/data_source.proto
Labels: enhancement
