Repository cloudforet-io/api, pull requests merged in 2024-09, with the labels that each got.

#413 Add 'match_workspace' rule at DataSourceRuleActions
  proto/spaceone/api/cost_analysis/v1/data_source_rule.proto
Labels: enhancement

#414 feat: modify 'permissions' and 'page_access' field type 'repeated str…
  proto/spaceone/api/identity/v2/role.proto
Labels: enhancement

#415 Fix type at collector rule request url(list, stat)
  proto/spaceone/api/inventory/v1/collector_rule.proto
Labels: bug

#416 Rollback role_binding_info to dictionary in workspace user
  proto/spaceone/api/identity/v2/workspace_user.proto
Labels: enhancement, pass/signedoff

#417 Update workspace and workspace group user
  proto/spaceone/api/identity/v2/workspace.proto
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#418 Remove workspaces of workspace_group_user_info
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: enhancement, pass/signedoff

#420 Remove redundancy
  proto/spaceone/api/identity/v2/workspace_group.proto
  proto/spaceone/api/identity/v2/workspace_group_user.proto
Labels: enhancement, pass/signedoff

#421 Add workspace_count field to workspace_group
  proto/spaceone/api/identity/v2/workspace_group.proto
Labels: enhancement, pass/signedoff

#422 Add changed_at to WorkspaceInfo
  proto/spaceone/api/identity/v2/workspace.proto
Labels: enhancement, pass/signedoff

#423 Add change folder api for public and private dashboard
  proto/spaceone/api/dashboard/v1/private_dashboard.proto
  proto/spaceone/api/dashboard/v1/public_dashboard.proto
Labels: enhancement

#424 Remove page_access field at GrantTokenInfo
  proto/spaceone/api/identity/v2/token.proto
Labels: enhancement

#425 Add new feature 'UnifiedCost' for Cost service
  proto/spaceone/api/cost_analysis/v1/unified_cost.proto
Labels: enhancement

#426 feat: add feature to share dashboard folder
  proto/spaceone/api/dashboard/v1/public_dashboard.proto
  proto/spaceone/api/dashboard/v1/public_folder.proto
Labels: pass/signedoff

#431 Add description of cloud service response model at inventory.CloudService
  proto/spaceone/api/inventory/v1/cloud_service.proto
Labels: documentation
