Repository cloudforet-io/api, pull requests merged in 2024-12, with the labels that each got.

#465 fix: add missing field
  proto/spaceone/api/opsflow/v1/event.proto
Labels: pass/signedoff

#467 Add identity service_Account analyze.
  proto/spaceone/api/identity/v2/service_account.proto
Labels: pass/signedoff

#468 fix: add include_category_fields parameter
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#469 fix: add created_by parameter
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/task.proto
Labels: pass/signedoff

#470 Add created_by field at collector info of inventory v2
  proto/spaceone/api/inventory_v2/v1/collector.proto
  template/python/setup.py.tmpl
Labels: enhancement

#471 Initial commit for alert manager.
  proto/spaceone/api/alert_manager/plugin/event.proto
  proto/spaceone/api/alert_manager/plugin/notification.proto
  proto/spaceone/api/alert_manager/plugin/protocol.proto
  proto/spaceone/api/alert_manager/plugin/webhook.proto
  proto/spaceone/api/alert_manager/v1/alert.proto
  proto/spaceone/api/alert_manager/v1/escalation_policy.proto
  proto/spaceone/api/alert_manager/v1/event.proto
  proto/spaceone/api/alert_manager/v1/event_rule.proto
  proto/spaceone/api/alert_manager/v1/note.proto
  proto/spaceone/api/alert_manager/v1/notification_protocol.proto
  proto/spaceone/api/alert_manager/v1/plugin/event.proto
  proto/spaceone/api/alert_manager/v1/plugin/webhook.proto
  proto/spaceone/api/alert_manager/v1/service.proto
  proto/spaceone/api/alert_manager/v1/service_channel.proto
  proto/spaceone/api/alert_manager/v1/user_channel.proto
  proto/spaceone/api/alert_manager/v1/user_group_channel.proto
  proto/spaceone/api/alert_manager/v1/webhook.proto
Labels: pass/signedoff

#478 Add examples for inventory_v2 Job
  proto/spaceone/api/inventory_v2/v1/collector.proto
  proto/spaceone/api/inventory_v2/v1/job.proto
Labels: documentation, pass/signedoff

#479 Add JobTask api interface for inventory v2
  proto/spaceone/api/inventory_v2/v1/job.proto
  proto/spaceone/api/inventory_v2/v1/job_task.proto
Labels: enhancement

#480 Fix Region api to identity-v2
  proto/spaceone/api/inventory_v2/v1/region.proto
Labels: enhancement, pass/signedoff

#487 Add Asset api interface for inventory v2
  proto/spaceone/api/inventory_v2/v1/asset.proto
Labels: enhancement

#482 feat: add namespacegroup, namespace api interface for inventory v2
  proto/spaceone/api/inventory_v2/v1/namespace.proto
  proto/spaceone/api/inventory_v2/v1/namespace_group.proto
Labels: enhancement, fail/signedoff

#489 fix: add state, deleted_at parameter
  proto/spaceone/api/opsflow/v1/task.proto
  proto/spaceone/api/opsflow/v1/task_category.proto
Labels: pass/signedoff

#494 Add get_accessible_configs api to PublicConfig
  proto/spaceone/api/config/v1/public_config.proto
  proto/spaceone/api/config/v1/workspace_config.proto
Labels: enhancement

#495 Add update password api to UserProfile
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement

#497 fix: fix alert info field name triggered_type
  proto/spaceone/api/alert_manager/v1/alert.proto
Labels: fail/signedoff

#500 fix: add escalation_policy repeat fields at update request
  proto/spaceone/api/alert_manager/v1/escalation_policy.proto
Labels: fail/signedoff

#508 fix: add vars, source parameter
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/event.proto
  proto/spaceone/api/opsflow/v1/task_category.proto
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#510 feat: add variable api to opsflow
  proto/spaceone/api/opsflow/v1/variable.proto
Labels: pass/signedoff

#512 fix: remove resource_group parameter
  proto/spaceone/api/opsflow/v1/variable.proto
Labels: pass/signedoff

#513 fix: add reference_id parameter to opsflow
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/task.proto
Labels: pass/signedoff
