Repository cloudforet-io/api, pull requests merged in 2025-02, with the labels that each got.

#556 Modify release workflow
  .github/workflows/dispatch_release.yaml
Labels: enhancement

#558 add: add schedule to data source request
  proto/spaceone/api/cost_analysis/v1/data_source.proto
Labels: fail/signedoff

#561 Add run method to UnifiedCost service and update proto definitions
  proto/spaceone/api/cost_analysis/v1/unified_cost.proto
Labels: enhancement

#562 Modify python package version for build
  pkg/pip_requirements.txt
Labels: bug
