Repository cloudforet-io/api, pull requests merged in 2025-01, with the labels that each got.

#531 fix: add scope, resource_group parameter to opsflow
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/event.proto
  proto/spaceone/api/opsflow/v1/task.proto
  proto/spaceone/api/opsflow/v1/task_category.proto
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#490 Add CollectorRule api to Identity-v2
  proto/spaceone/api/identity/v2/endpoint.proto
  proto/spaceone/api/inventory_v2/v1/collector_rule.proto
Labels: enhancement, fail/signedoff, pass/signedoff

#533 fix: remove scope, resource_group parameter to opsflow
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/task.proto
  proto/spaceone/api/opsflow/v1/task_type.proto
Labels: pass/signedoff

#535 feat: add project_id field to file requests and rename userfile.proto to user_file.proto
  dist/python/spaceone/api/file_manager/v1/file_pb2.py
  dist/python/spaceone/api/file_manager/v1/user_file_pb2.py
  dist/python/spaceone/api/file_manager/v1/user_file_pb2_grpc.py
  proto/spaceone/api/file_manager/v1/file.proto
  proto/spaceone/api/file_manager/v1/user_file.proto
Labels: fail/signedoff

#537 feat: add optional contents_type field to CreatePostRequest and UpdatePostRequest
  dist/python/spaceone/api/board/v1/post_pb2.py
  proto/spaceone/api/board/v1/post.proto
Labels: fail/signedoff

#540 feat: add optional project_id field to UpdateFileRequest
  proto/spaceone/api/file_manager/v1/file.proto
Labels: enhancement, fail/signedoff

#541 feat: add contents_type field to TaskInfo, CommentInfo
  proto/spaceone/api/opsflow/v1/comment.proto
  proto/spaceone/api/opsflow/v1/task.proto
Labels: pass/signedoff

#551 feat: add an alert action
  proto/spaceone/api/alert_manager/v1/alert.proto
Labels: pass/signedoff

#553 Remove password field from UserProfile Update
  proto/spaceone/api/identity/v2/user_profile.proto
Labels: enhancement, pass/signedoff

#555 Add task_changed field at job task info
  proto/spaceone/api/cost_analysis/plugin/job.proto
  proto/spaceone/api/cost_analysis/v1/job.proto
  proto/spaceone/api/cost_analysis/v1/job_task.proto
Labels: enhancement, pass/signedoff
